server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: client
          uri: lb://SPRING-CLOUD-EUREKA-CLIENT
          predicates:
            - Path=/**
